### ISSUE TITLE
Problem on startup app windows....

### ISSUE THREAD

**Issue by maiconmva** [laradumps/app#301]
after a have set the shortcut to CTRL + SHIFT + R to show, and CTRL + SHIFT + E to clean.. starts this error, i cant use app.

[image](https://github.com/laradumps/app/assets/5194641/11889652-0087-436b-b4ee-b9812c727558)

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Unvalid accelerator: "⊞+Shift+R"
    at W8 (C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:90:38607)
    at Object.xO [as register] (C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:96:1872)
    at C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:122:6126
    at C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:90:31188
    at C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:90:29932
    at C:\Users\maico\AppData\Local\Programs\LaraDumps\resources\app.asar\dist\main.js:90:26272
    at FSReqCallback.oncomplete (node:fs:191:23)

[OK]

**Comment by maiconmva** [comment]
ii have tried to uninstall, femove folders.. problem still..

**Comment by maiconmva** [comment]
![image](https://github.com/user-attachments/assets/96753adf-b312-43b8-ab92-9e6490995851)
